// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpveNjVZvEYUd-GObaKcRgCKGH9v4qbR8',
    appId: '1:810487422984:web:ea0c8d9d3c8ce37e6971bd',
    messagingSenderId: '810487422984',
    projectId: 'phoneauth-f3046',
    authDomain: 'phoneauth-f3046.firebaseapp.com',
    storageBucket: 'phoneauth-f3046.appspot.com',
    measurementId: 'G-Y7GFBHGLJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_9VI0g6HiGWMJFWlZYFZuuFzBGWHhIQg',
    appId: '1:810487422984:android:fc9fd16078551d2b6971bd',
    messagingSenderId: '810487422984',
    projectId: 'phoneauth-f3046',
    storageBucket: 'phoneauth-f3046.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwrv_VXAcVOZR2Z9k9BDyiLgaW5Td6X64',
    appId: '1:810487422984:ios:74d2952c51ddf94d6971bd',
    messagingSenderId: '810487422984',
    projectId: 'phoneauth-f3046',
    storageBucket: 'phoneauth-f3046.appspot.com',
    iosBundleId: 'com.example.flutterDemoApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwrv_VXAcVOZR2Z9k9BDyiLgaW5Td6X64',
    appId: '1:810487422984:ios:74d2952c51ddf94d6971bd',
    messagingSenderId: '810487422984',
    projectId: 'phoneauth-f3046',
    storageBucket: 'phoneauth-f3046.appspot.com',
    iosBundleId: 'com.example.flutterDemoApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpveNjVZvEYUd-GObaKcRgCKGH9v4qbR8',
    appId: '1:810487422984:web:07ea6164e3730b796971bd',
    messagingSenderId: '810487422984',
    projectId: 'phoneauth-f3046',
    authDomain: 'phoneauth-f3046.firebaseapp.com',
    storageBucket: 'phoneauth-f3046.appspot.com',
    measurementId: 'G-M53NGCL496',
  );
}
